=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class DNSRecordTypesEnum
    A = "A".freeze
    AAAA = "AAAA".freeze
    ALIAS = "ALIAS".freeze
    CAA = "CAA".freeze
    CNAME = "CNAME".freeze
    IPS = "IPS".freeze
    MX = "MX".freeze
    NS = "NS".freeze
    PTR = "PTR".freeze
    SOA = "SOA".freeze
    SRV = "SRV".freeze
    SSHFP = "SSHFP".freeze
    TXT = "TXT".freeze
    VIRTUAL_MACHINE = "VirtualMachine".freeze

    def self.all_vars
      @all_vars ||= [A, AAAA, ALIAS, CAA, CNAME, IPS, MX, NS, PTR, SOA, SRV, SSHFP, TXT, VIRTUAL_MACHINE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DNSRecordTypesEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DNSRecordTypesEnum"
    end
  end
end
