=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class DNSRecordTypeEnum
    A = "a".freeze
    AAAA = "aaaa".freeze
    CAA = "caa".freeze
    CNAME = "cname".freeze
    MX = "mx".freeze
    NS = "ns".freeze
    SRV = "srv".freeze
    SSHFP = "sshfp".freeze
    TXT = "txt".freeze
    VIRTUAL_MACHINE = "virtual_machine".freeze
    ALIAS = "alias".freeze

    def self.all_vars
      @all_vars ||= [A, AAAA, CAA, CNAME, MX, NS, SRV, SSHFP, TXT, VIRTUAL_MACHINE, ALIAS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DNSRecordTypeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DNSRecordTypeEnum"
    end
  end
end
