=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class InfrastructureDNSZoneCannotBeEditedEnum
    INFRASTRUCTURE_DNS_ZONE_CANNOT_BE_EDITED = "infrastructure_dns_zone_cannot_be_edited".freeze

    def self.all_vars
      @all_vars ||= [INFRASTRUCTURE_DNS_ZONE_CANNOT_BE_EDITED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if InfrastructureDNSZoneCannotBeEditedEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #InfrastructureDNSZoneCannotBeEditedEnum"
    end
  end
end
