=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class PatchVirtualMachine200ResponseVirtualMachineOrganization
    attr_accessor :id

    attr_accessor :name

    attr_accessor :sub_domain

    attr_accessor :infrastructure_domain

    attr_accessor :created_at

    attr_accessor :suspended

    attr_accessor :managed

    attr_accessor :billing_name

    attr_accessor :address1

    attr_accessor :address2

    attr_accessor :address3

    attr_accessor :address4

    attr_accessor :postcode

    attr_accessor :vat_number

    attr_accessor :phone_number

    attr_accessor :currency

    attr_accessor :country

    attr_accessor :country_state

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'sub_domain' => :'sub_domain',
        :'infrastructure_domain' => :'infrastructure_domain',
        :'created_at' => :'created_at',
        :'suspended' => :'suspended',
        :'managed' => :'managed',
        :'billing_name' => :'billing_name',
        :'address1' => :'address1',
        :'address2' => :'address2',
        :'address3' => :'address3',
        :'address4' => :'address4',
        :'postcode' => :'postcode',
        :'vat_number' => :'vat_number',
        :'phone_number' => :'phone_number',
        :'currency' => :'currency',
        :'country' => :'country',
        :'country_state' => :'country_state'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'sub_domain' => :'String',
        :'infrastructure_domain' => :'String',
        :'created_at' => :'Integer',
        :'suspended' => :'Boolean',
        :'managed' => :'Boolean',
        :'billing_name' => :'String',
        :'address1' => :'String',
        :'address2' => :'String',
        :'address3' => :'String',
        :'address4' => :'String',
        :'postcode' => :'String',
        :'vat_number' => :'String',
        :'phone_number' => :'String',
        :'currency' => :'PatchVirtualMachine200ResponseVirtualMachineOrganizationCurrency',
        :'country' => :'PatchVirtualMachine200ResponseVirtualMachineOrganizationCountry',
        :'country_state' => :'PatchVirtualMachine200ResponseVirtualMachineOrganizationCountryState'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `KatapultAPI::PatchVirtualMachine200ResponseVirtualMachineOrganization` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `KatapultAPI::PatchVirtualMachine200ResponseVirtualMachineOrganization`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'sub_domain')
        self.sub_domain = attributes[:'sub_domain']
      end

      if attributes.key?(:'infrastructure_domain')
        self.infrastructure_domain = attributes[:'infrastructure_domain']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'suspended')
        self.suspended = attributes[:'suspended']
      end

      if attributes.key?(:'managed')
        self.managed = attributes[:'managed']
      end

      if attributes.key?(:'billing_name')
        self.billing_name = attributes[:'billing_name']
      end

      if attributes.key?(:'address1')
        self.address1 = attributes[:'address1']
      end

      if attributes.key?(:'address2')
        self.address2 = attributes[:'address2']
      end

      if attributes.key?(:'address3')
        self.address3 = attributes[:'address3']
      end

      if attributes.key?(:'address4')
        self.address4 = attributes[:'address4']
      end

      if attributes.key?(:'postcode')
        self.postcode = attributes[:'postcode']
      end

      if attributes.key?(:'vat_number')
        self.vat_number = attributes[:'vat_number']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'country_state')
        self.country_state = attributes[:'country_state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          sub_domain == o.sub_domain &&
          infrastructure_domain == o.infrastructure_domain &&
          created_at == o.created_at &&
          suspended == o.suspended &&
          managed == o.managed &&
          billing_name == o.billing_name &&
          address1 == o.address1 &&
          address2 == o.address2 &&
          address3 == o.address3 &&
          address4 == o.address4 &&
          postcode == o.postcode &&
          vat_number == o.vat_number &&
          phone_number == o.phone_number &&
          currency == o.currency &&
          country == o.country &&
          country_state == o.country_state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, sub_domain, infrastructure_domain, created_at, suspended, managed, billing_name, address1, address2, address3, address4, postcode, vat_number, phone_number, currency, country, country_state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = KatapultAPI.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
