=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class TagColorsEnum
    RED = "red".freeze
    PINK = "pink".freeze
    PURPLE = "purple".freeze
    DARK_BLUE = "dark_blue".freeze
    GREEN = "green".freeze
    TEAL = "teal".freeze
    AQUA = "aqua".freeze
    LIGHT_BLUE = "light_blue".freeze
    YELLOW = "yellow".freeze
    ORANGE = "orange".freeze
    ORANGE_RED = "orange_red".freeze
    BROWN = "brown".freeze
    BLACK = "black".freeze
    DARK_GRAY = "dark_gray".freeze
    LIGHT_GRAY = "light_gray".freeze
    LIGHT_BROWN = "light_brown".freeze
    PASTEL_RED = "pastel_red".freeze
    PASTEL_PINK = "pastel_pink".freeze
    PASTEL_PURPLE = "pastel_purple".freeze
    PASTEL_DARK_BLUE = "pastel_dark_blue".freeze
    PASTEL_GREEN = "pastel_green".freeze
    PASTEL_TEAL = "pastel_teal".freeze
    PASTEL_AQUA = "pastel_aqua".freeze
    PASTEL_LIGHT_BLUE = "pastel_light_blue".freeze
    PASTEL_YELLOW = "pastel_yellow".freeze
    PASTEL_ORANGE = "pastel_orange".freeze
    PASTEL_ORANGE_RED = "pastel_orange_red".freeze
    PASTEL_BROWN = "pastel_brown".freeze
    PASTEL_BLACK = "pastel_black".freeze
    PASTEL_DARK_GRAY = "pastel_dark_gray".freeze
    PASTEL_LIGHT_GRAY = "pastel_light_gray".freeze
    PASTEL_LIGHT_BROWN = "pastel_light_brown".freeze

    def self.all_vars
      @all_vars ||= [RED, PINK, PURPLE, DARK_BLUE, GREEN, TEAL, AQUA, LIGHT_BLUE, YELLOW, ORANGE, ORANGE_RED, BROWN, BLACK, DARK_GRAY, LIGHT_GRAY, LIGHT_BROWN, PASTEL_RED, PASTEL_PINK, PASTEL_PURPLE, PASTEL_DARK_BLUE, PASTEL_GREEN, PASTEL_TEAL, PASTEL_AQUA, PASTEL_LIGHT_BLUE, PASTEL_YELLOW, PASTEL_ORANGE, PASTEL_ORANGE_RED, PASTEL_BROWN, PASTEL_BLACK, PASTEL_DARK_GRAY, PASTEL_LIGHT_GRAY, PASTEL_LIGHT_BROWN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TagColorsEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TagColorsEnum"
    end
  end
end
