=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'date'
require 'time'

module KatapultAPI
  class VirtualMachineStateEnum
    STOPPED = "stopped".freeze
    FAILED = "failed".freeze
    STARTED = "started".freeze
    STARTING = "starting".freeze
    ALLOCATED = "allocated".freeze
    ALLOCATING = "allocating".freeze
    RESETTING = "resetting".freeze
    MIGRATING = "migrating".freeze
    STOPPING = "stopping".freeze
    SHUTTING_DOWN = "shutting_down".freeze
    TRANSFERRING = "transferring".freeze
    ORPHANED = "orphaned".freeze

    def self.all_vars
      @all_vars ||= [STOPPED, FAILED, STARTED, STARTING, ALLOCATED, ALLOCATING, RESETTING, MIGRATING, STOPPING, SHUTTING_DOWN, TRANSFERRING, ORPHANED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if VirtualMachineStateEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #VirtualMachineStateEnum"
    end
  end
end
