=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::DeleteVirtualMachine200ResponseVirtualMachineGroup
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::DeleteVirtualMachine200ResponseVirtualMachineGroup do
  let(:instance) { KatapultAPI::DeleteVirtualMachine200ResponseVirtualMachineGroup.new }

  describe 'test an instance of DeleteVirtualMachine200ResponseVirtualMachineGroup' do
    it 'should create an instance of DeleteVirtualMachine200ResponseVirtualMachineGroup' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::DeleteVirtualMachine200ResponseVirtualMachineGroup)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "segregate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "auto_segregate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
