=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::DeleteFileStorageVolume200ResponseFileStorageVolume
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::DeleteFileStorageVolume200ResponseFileStorageVolume do
  let(:instance) { KatapultAPI::DeleteFileStorageVolume200ResponseFileStorageVolume.new }

  describe 'test an instance of DeleteFileStorageVolume200ResponseFileStorageVolume' do
    it 'should create an instance of DeleteFileStorageVolume200ResponseFileStorageVolume' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::DeleteFileStorageVolume200ResponseFileStorageVolume)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_center"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "associations"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "nfs_location"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
