=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::DeleteLoadBalancersRulesLoadBalancerRuleRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::DeleteLoadBalancersRulesLoadBalancerRuleRequest do
  let(:instance) { KatapultAPI::DeleteLoadBalancersRulesLoadBalancerRuleRequest.new }

  describe 'test an instance of DeleteLoadBalancersRulesLoadBalancerRuleRequest' do
    it 'should create an instance of DeleteLoadBalancersRulesLoadBalancerRuleRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::DeleteLoadBalancersRulesLoadBalancerRuleRequest)
    end
  end

  describe 'test attribute "load_balancer_rule"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
