=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::DNSRecordContentArgumentsForSSHFP
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::DNSRecordContentArgumentsForSSHFP do
  let(:instance) { KatapultAPI::DNSRecordContentArgumentsForSSHFP.new }

  describe 'test an instance of DNSRecordContentArgumentsForSSHFP' do
    it 'should create an instance of DNSRecordContentArgumentsForSSHFP' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::DNSRecordContentArgumentsForSSHFP)
    end
  end

  describe 'test attribute "algorithm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fingerprint_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fingerprint"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
