=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetDiskTemplateVersions200ResponseDiskTemplateVersions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetDiskTemplateVersions200ResponseDiskTemplateVersions do
  let(:instance) { KatapultAPI::GetDiskTemplateVersions200ResponseDiskTemplateVersions.new }

  describe 'test an instance of GetDiskTemplateVersions200ResponseDiskTemplateVersions' do
    it 'should create an instance of GetDiskTemplateVersions200ResponseDiskTemplateVersions' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetDiskTemplateVersions200ResponseDiskTemplateVersions)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "stable"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "size_in_gb"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
