=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetDiskTemplateVersions200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetDiskTemplateVersions200Response do
  let(:instance) { KatapultAPI::GetDiskTemplateVersions200Response.new }

  describe 'test an instance of GetDiskTemplateVersions200Response' do
    it 'should create an instance of GetDiskTemplateVersions200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetDiskTemplateVersions200Response)
    end
  end

  describe 'test attribute "disk_template"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "disk_template_versions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
