=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild do
  let(:instance) { KatapultAPI::GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild.new }

  describe 'test an instance of GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild' do
    it 'should create an instance of GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetVirtualMachinesBuildsVirtualMachineBuild200ResponseVirtualMachineBuild)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "spec_xml"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "virtual_machine"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
