=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetOrganizationCertificates200ResponseCertificates
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetOrganizationCertificates200ResponseCertificates do
  let(:instance) { KatapultAPI::GetOrganizationCertificates200ResponseCertificates.new }

  describe 'test an instance of GetOrganizationCertificates200ResponseCertificates' do
    it 'should create an instance of GetOrganizationCertificates200ResponseCertificates' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetOrganizationCertificates200ResponseCertificates)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "issuer"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expires_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_issued_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
