=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetLoadBalancersRulesLoadBalancerRule404Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetLoadBalancersRulesLoadBalancerRule404Response do
  let(:instance) { KatapultAPI::GetLoadBalancersRulesLoadBalancerRule404Response.new }

  describe 'test an instance of GetLoadBalancersRulesLoadBalancerRule404Response' do
    it 'should create an instance of GetLoadBalancersRulesLoadBalancerRule404Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetLoadBalancersRulesLoadBalancerRule404Response)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["load_balancer_rule_not_found"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "detail"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
