=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule do
  let(:instance) { KatapultAPI::GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule.new }

  describe 'test an instance of GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule' do
    it 'should create an instance of GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetDiskBackupPolicy200ResponseDiskBackupPolicySchedule)
    end
  end

  describe 'test attribute "frequency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "interval"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "minute"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_invocation_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
