=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress do
  let(:instance) { KatapultAPI::GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress.new }

  describe 'test an instance of GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress' do
    it 'should create an instance of GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetOrganizationLoadBalancers200ResponseLoadBalancersIPAddress)
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
