=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::GetVirtualMachine200ResponseVirtualMachineOrganizationCountry
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::GetVirtualMachine200ResponseVirtualMachineOrganizationCountry do
  let(:instance) { KatapultAPI::GetVirtualMachine200ResponseVirtualMachineOrganizationCountry.new }

  describe 'test an instance of GetVirtualMachine200ResponseVirtualMachineOrganizationCountry' do
    it 'should create an instance of GetVirtualMachine200ResponseVirtualMachineOrganizationCountry' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::GetVirtualMachine200ResponseVirtualMachineOrganizationCountry)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "iso_code2"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "iso_code3"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "time_zone"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "eu"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
