=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::InvalidAPITokenEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::InvalidAPITokenEnum do
  let(:instance) { KatapultAPI::InvalidAPITokenEnum.new }

  describe 'test an instance of InvalidAPITokenEnum' do
    it 'should create an instance of InvalidAPITokenEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::InvalidAPITokenEnum)
    end
  end

end
