=begin
#Katapult Core API

#Welcome to the documentation for the Katapult Core API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KatapultAPI::PostOrganizationManaged201ResponseOrganizationCurrency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KatapultAPI::PostOrganizationManaged201ResponseOrganizationCurrency do
  let(:instance) { KatapultAPI::PostOrganizationManaged201ResponseOrganizationCurrency.new }

  describe 'test an instance of PostOrganizationManaged201ResponseOrganizationCurrency' do
    it 'should create an instance of PostOrganizationManaged201ResponseOrganizationCurrency' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KatapultAPI::PostOrganizationManaged201ResponseOrganizationCurrency)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "iso_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "symbol"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
